name: Build macOS App with py2app

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install py2app PyMuPDF Pillow imagehash

      - name: Build .app with py2app
        run: |
          python setup.py py2app

      - name: Create .dmg installer
        run: |
          brew install create-dmg
          create-dmg dist/PDFDiffTool.app \
            --overwrite \
            --dmg-title="PDFDiffTool Installer" \
            --app-drop-link 600 185 \
            dist/PDFDiffTool.dmg

      - name: Upload built .app and .dmg
        uses: actions/upload-artifact@v4
        with:
          name: PDFDiffTool-macOS
          path: |
            dist/PDFDiffTool.app
            dist/PDFDiffTool.dmg
